### ISSUE TITLE
Question: Service on same IP (cmd/register) is not found by cmd/browse

### ISSUE THREAD

**Issue by jurgen-kluft** [brutella/dnssd#13]
Is this expected behavior ?

Edit: When i run cmd/register on another device then this service is detected by cmd/browse

**Comment by brutella** [comment]
This is not expected behaviour and might be related to [setting multicast loopback to false](https://github.com/brutella/dnssd/blob/master/mdns.go#L128).

**Comment by jurgen-kluft** [comment]
Yup, when i set this (SetMulticastLoopback) to ``true`` it will find services running on the same device.

**Comment by brutella** [comment]
Could you please test the `multicast-loopback` branch. There all multicast loopback packets are ignored during probing.

**Comment by jurgen-kluft** [comment]
tested the ``multicast-loopback`` branch and now both remote and local processes are listed correctly.
