### ISSUE TITLE
Known-Answer Suppression (RFC6762 7.1.)

### ISSUE THREAD

**Issue by tmm1** [brutella/dnssd#2]
Hi, I've contributed to oleksandr/bonjour and it's fork grandcat/zeroconf in the past. Happy to see another dnssd library with a clean approach and conformance tests.

Does dnssd support known-answer suppression? I added it to grandcat/zeroconf earlier this year after noticing a lot of unnecessary bonjour traffic on the network.

https://github.com/grandcat/zeroconf/blob/8219919fca892353a082b184bca66db55c55b583/server.go#L348-L372

**Comment by tmm1** [comment]
Ah, I think I found where it's happening: https://github.com/brutella/dnssd/blob/36a2d8c541aab14895fc5492d5ad8ec447a67c47/dns.go#L205

**Comment by brutella** [comment]
Yes, it does have known-answer suppression.
