### ISSUE TITLE
Question: Refactoring branch

### ISSUE THREAD

**Issue by makon** [brutella/dnssd#25]
Thanks for your great work with this project.

We are currently facing the issue that for IPv6 link local the interface name is needed to establish a connection.
You implemented this feature in your `refactoring` branch along with other fixes like e45ff4e7af784a8f6e8a0adac2934fa6bccc0b90.

Now i wonder if there is a reason why the branch was not merged into master. On a first glance it works stable. Are there some open issues? Do you think the `refactoring` branch can be used in production?

**Comment by brutella** [comment]
Because of #15 #16 #18

**Comment by brutella** [comment]
#15 and #18 should be fixed now in the `refactoring` branch.

**Comment by brutella** [comment]
The refactoring branch is now merged 🎉
