### ISSUE TITLE
Dealing with IP changes

### ISSUE THREAD

**Issue by tmm1** [brutella/dnssd#3]
Sometimes DHCP or manual changes can cause a computer's IP address to change. It looks like dnssd currently caches the IPs in the Service's IfaceIPs. This means the incorrect IP will be included in mdns responses.

**Comment by brutella** [comment]
Correct, this library doesn't observe IP address changes.

**Comment by tmm1** [comment]
To get events when network interface IPs change you can use https://stackoverflow.com/questions/36347807/how-to-monitor-ip-address-change-using-rtnetlink-socket-in-go-language

**Comment by brutella** [comment]
Changes to network interfaces are now observed on Linux using netlink since version `v.1.2.12`. Which means that services are re-announced when for example an Ethernet cable is plugged in.
