### ISSUE TITLE
Bug: NewResponder should not have to listen on all interfaces

### ISSUE THREAD

**Issue by upsampled** [brutella/dnssd#46]
I am running this library as a server and noticed that even though I only included one interface in the `dnssd.Config`, I was seeing IGMP messages on both interfaces.  This was confirmed running `-Verbose` flag in the `cmd/register`:
```
# register -Name "TSTService" -Type "_tst._tcp" -Port 9876 -Interface eth1 -Verbose
18:09:36.417    ...STARTING...
DEBUG 2024/05/13 18:09:36.432281 mdns.go:183: Joined IPv4 eth1
DEBUG 2024/05/13 18:09:36.434637 mdns.go:183: Joined IPv4 wwan0
DEBUG 2024/05/13 18:09:36.446972 mdns.go:204: Joined IPv6 eth1
DEBUG 2024/05/13 18:09:36.449525 mdns.go:204: Joined IPv6 wwan0
```
Not sure if the interfaces listed in `dnssd.Config` should be the only interfaces listened on, but there should at least be a way to limited the interfaces being used.

**Comment by brutella** [comment]
Thanks for bringing up this issue.

This is now fixed by [91c1c03](https://github.com/brutella/dnssd/commit/91c1c03a61e63eaf885854c3d7bc9afd0df05827)
