### ISSUE TITLE
DNS answers/queries should only include A/AAAA records for a specific network interface

### ISSUE THREAD

**Issue by brutella** [brutella/dnssd#8]
Currently when sending probe and announcement messages, all A (ip v4) and AAAA (ip v6) records from all network interfaces are included.

We should also provide an option to advertise on specific network interfaces only.

**Comment by tmm1** [comment]
FYI, there is example code in https://stackoverflow.com/questions/36347807 to detect when Linux and BSD based systems change IPs on network interfaces due to DHCP, etc.
